version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
  db-migrations:
    build: 
      context: .
      dockerfile: Dockerfile.migration
    depends_on:
      - db
    restart: on-failure
#    environment:
#      DB_CONNECTION: "Server=db;Database=Contoso_Authentication_Logs;Trusted_Connection=True;User Id=sa;Password=Your_password123;"
    