version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"